### ISSUE TITLE
大佬配置文件都填好了怎么打开主页是空白？

### ISSUE THREAD

**Issue by 24021438** [xytoki/TCShare#11]
大佬配置文件都填好了怎么打开主页是空白？
![Lily_Screenshot_2020年02月13日05时07分26秒](https://user-images.githubusercontent.com/56147487/74381494-84aee680-4e26-11ea-82d1-189a16d746be.png)
![111](https://user-images.githubusercontent.com/56147487/74381497-8678aa00-4e26-11ea-9c28-0e84cb0413d8.png)

**Comment by 24021438** [comment]
![Lily_Screenshot_2020年02月13日05时07分26秒](https://user-images.githubusercontent.com/56147487/74377475-ebc89d00-4e1e-11ea-8234-bb179d2ca80d.png)

**Comment by 24021438** [comment]
![111](https://user-images.githubusercontent.com/56147487/74378737-76aa9700-4e21-11ea-926b-a957a61972d9.png)
我确定了一下应该是我开发平台回调导致的，我是用的官方sdk手动测试得到的ACCESS_TOKEN

**Comment by xytoki** [comment]
空白一般是apikey错误。

**Comment by 24021438** [comment]
api后台回调是要填127.0.0.1/-install么？

**Comment by xytoki** [comment]
是。但是api已经无法申请。
