### ISSUE TITLE
出现这个

### ISSUE THREAD

**Issue by qazwse4541** [xytoki/TCShare#12]
500 Internal Server Error
请正确配置Key (0)
#0 /volume1/app/ty/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(167): {closure}()
#1 /volume1/app/ty/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(145): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#2 /volume1/app/ty/_app/vendor/mikecao/flight/flight/Engine.php(340): flight\core\Dispatcher::execute(Object(Closure), Array)
#3 /volume1/app/ty/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(198): flight\Engine->_start()
#4 /volume1/app/ty/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(144): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 /volume1/app/ty/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(49): flight\core\Dispatcher::execute(Array, Array)
#6 /volume1/app/ty/_app/vendor/mikecao/flight/flight/Engine.php(92): flight\core\Dispatcher->run('start', Array)
#7 /volume1/app/ty/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(198): flight\Engine->__call('start', Array)
#8 /volume1/app/ty/_app/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)
#9 /volume1/app/ty/index.php(57): Flight::__callStatic('start', Array)
#10 {main}

**Comment by qazwse4541** [comment]
{"errormsg":"PermissionDenied","success":false}

**Comment by xytoki** [comment]
提示请正确配置Key可以放一下config.php(token打码)，应该是挂载设置错了。PermissionDenied是你用的apikey废了。

**Comment by qazwse4541** [comment]
apikey怎么申请呢

**Comment by qazwse4541** [comment]
{"errormsg":"InvalidSignature","success":false}

**Comment by qazwse4541** [comment]
https://github.com/gonewind73/scrapy/blob/9a18248c9cfa5020d4124a4b7c4d579b2ed70b34/cloud189Disk.py

**Comment by qazwse4541** [comment]
这里的能不能用啊

**Comment by xytoki** [comment]
InvalidSignature是apikey和secretkey不对应。不回答申请相关问题。
