### ISSUE TITLE
希望能增加其他格式的视频文件在线预览，感谢开源

### ISSUE THREAD

**Issue by TheEnd233** [xytoki/TCShare#15]
**What feature do you want?**
希望能增加其他格式的视频文件在线预览

**Describe the solution you'd like**
无脑的喷子处处都有，别特意放在心上吖~

**Additional context**
晓羽大佬加油

**Comment by xytoki** [comment]
天翼云视频文件不支持跨域，所以能支持的格式极为有限，如果硬要支持可能会需要服务器中转。

**Comment by TheEnd233** [comment]
> 天翼云视频文件不支持跨域，所以能支持的格式极为有限，如果硬要支持可能会需要服务器中转。

emm...可是我看到其他用cookie的挂载天翼盘的程序貌似都支持mkv文件。。。您可以参考一下这个

https://disk.ml.mk/video%E8%A7%86%E9%A2%91/

**Comment by xytoki** [comment]
mkv已经加上。
cb2b704627d551c816fa96747a2ca9a6a7778424
