### ISSUE TITLE
大佬，SCF更新后出错了

### ISSUE THREAD

**Issue by damonliguo** [xytoki/TCShare#17]
**Screenshots 截图/报错日志**
返回数据:

{"errorCode":-1,"errorMessage":"User process exit when running"}

日志:

START RequestId: 33bddf956ca19d6f517579b430d44f80

Event RequestId: 33bddf956ca19d6f517579b430d44f80

<h1>500 Internal Server Error</h1><h3>Class '' not found (0)</h3><pre>#0 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(169): {closure}(Object(flight\net\Route))

#1 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(145): flight\core\Dispatcher::callFunction(Object(Closure), Array)

#2 /var/user/_app/vendor/mikecao/flight/flight/Engine.php(340): flight\core\Dispatcher::execute(Object(Closure), Array)

#3 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(210): flight\Engine->_start(Object(stdClass), Object(stdClass), '/var/user')

#4 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(144): flight\core\Dispatcher::invokeMethod(Array, Array)

#5 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(49): flight\core\Dispatcher::execute(Array, Array)

#6 /var/user/_app/vendor/mikecao/flight/flight/Engine.php(92): flight\core\Dispatcher->run('start', Array)

#7 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(210): flight\Engine->__call('start', Array)

#8 /var/user/_app/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)

#9 /var/user/index.php(64): Flight::__callStatic('start', Array)

#10 /var/runtime/php7/bootstrap.php(41): main_handler(Object(stdClass), Object(stdClass))

#11 /var/runtime/php7/bootstrap.php(191): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass))

#12 /var/runtime/php7/bootstrap.php(214): __scf_bootstrap_\__main_for_scf()

#13 {main}</pre> 

ERROR RequestId:33bddf956ca19d6f517579b430d44f80 Result:{"errorCode":-1,"errorMessage":"User process exit when running"} 

END RequestId: 33bddf956ca19d6f517579b430d44f80

Report RequestId: 33bddf956ca19d6f517579b430d44f80 Duration:16ms Memory:128MB MemUsage:14.000000MB

**Comment by xytoki** [comment]
已发新版，麻烦测试一下。

**Comment by xytoki** [comment]
现在在开发自动安装，不用写配置文件那种，所以比较容易出问题。

**Comment by damonliguo** [comment]
返回数据:

{"errorCode":-1,"errorMessage":"User process exit when running"}

日志:

START RequestId: 32b9c123a302c1faa3c67fb1fedafa79

Event RequestId: 32b9c123a302c1faa3c67fb1fedafa79

<h1>500 Internal Server Error</h1><h3>Class '' not found (0)</h3><pre>#0 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(169): {closure}(Object(flight\net\Route))

#1 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(145): flight\core\Dispatcher::callFunction(Object(Closure), Array)

#2 /var/user/_app/vendor/mikecao/flight/flight/Engine.php(340): flight\core\Dispatcher::execute(Object(Closure), Array)

#3 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(210): flight\Engine->_start(Object(stdClass), Object(stdClass), '/var/user')

#4 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(144): flight\core\Dispatcher::invokeMethod(Array, Array)

#5 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(49): flight\core\Dispatcher::execute(Array, Array)

#6 /var/user/_app/vendor/mikecao/flight/flight/Engine.php(92): flight\core\Dispatcher->run('start', Array)

#7 /var/user/_app/vendor/mikecao/flight/flight/core/Dispatcher.php(210): flight\Engine->__call('start', Array)

#8 /var/user/_app/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)

#9 /var/user/index.php(68): Flight::__callStatic('start', Array)

#10 /var/runtime/php7/bootstrap.php(41): main_handler(Object(stdClass), Object(stdClass))

#11 /var/runtime/php7/bootstrap.php(191): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass))

#12 /var/runtime/php7/bootstrap.php(214): __scf_bootstrap_\__main_for_scf()

#13 {main}</pre> 

ERROR RequestId:32b9c123a302c1faa3c67fb1fedafa79 Result:{"errorCode":-1,"errorMessage":"User process exit when running"} 

END RequestId: 32b9c123a302c1faa3c67fb1fedafa79

Report RequestId: 32b9c123a302c1faa3c67fb1fedafa79 Duration:15ms Memory:128MB MemUsage:14.230469MB

**Comment by xytoki** [comment]
能否提供一下脱敏的config.php？
或者尝试一下在scf后台设一下环境变量
```bash
XS_KEY_ct=ctyun
XS_KEY_ct_FD=     #FD
XS_KEY_ct_AK=     #AK
XS_KEY_ct_SK=     #SK
XS_KEY_ct_ACCESS_TOKEN=     #access token
XS_APP_1_NAME=          #名字
XS_APP_1_THEME=mdui #主题
XS_APP_1_BASE=/
XS_APP_1_KEY=ct
XS_APP_1=/ #挂载路径
```

**Comment by xytoki** [comment]
（设环境变量的话，config.php里的配置要删掉，不能并存

**Comment by damonliguo** [comment]
我试试

**Comment by damonliguo** [comment]
配置环境变量后测试运行正常

**Comment by xytoki** [comment]
好的。config.php的问题我再排查一下。
