### ISSUE TITLE
能不能对接B站播放器啊

### ISSUE THREAD

**Issue by 56025192** [xytoki/TCShare#19]
**What feature do you want?**
请清晰描述你想要的功能
能不能对接B站播放器啊

**Describe the solution you'd like**
如果可以，请尝试提出可能的解决方案
播放器下载地址
https://www.pohaier.com/usr/uploads/2020/02/3238287162.zip

**Additional context**
其他你想说的

**Comment by xytoki** [comment]
不用闭源项目，请自己修改主题。
