### ISSUE TITLE
TCShare部署到SCF上后绑定域名问题

### ISSUE THREAD

**Issue by hokyouni** [xytoki/TCShare#21]
识别路径出错，就是主页为example.com，点开文件夹（假设为123）就变为example.com/release/程序名/123
感觉这并不是程序的Bug
看图：
https://s2.ax1x.com/2020/02/22/3MvLSf.gif

贴几处重要配置：
https://s2.ax1x.com/2020/02/22/3Qk09H.png
https://s2.ax1x.com/2020/02/22/3QkrjI.png

**Comment by xytoki** [comment]
是bug。已定位，有空就修复，请耐心等待。

**Comment by xytoki** [comment]
xytoki/scf-flight#1

**Comment by xytoki** [comment]
已修复。
请升级2.7，然后增加一条环境变量：scf_base=/，其中/是绑定的路径
