### ISSUE TITLE
我又来反馈bug了

### ISSUE THREAD

**Issue by damonliguo** [xytoki/TCShare#25]
**Describe the bug 症状是什么？**
视频无法播放了

**Screenshots 截图/报错日志**
返回数据:

{"errorCode":-1,"errorMessage":"User process exit when running"}

日志:

START RequestId: ef08b08ab3e2296819a40f0ef82fc2cc

Event RequestId: ef08b08ab3e2296819a40f0ef82fc2cc

 

ERROR RequestId:ef08b08ab3e2296819a40f0ef82fc2cc Result:{"errorCode":-1,"errorMessage":"User process exit when running"} 

END RequestId: ef08b08ab3e2296819a40f0ef82fc2cc

Report RequestId: ef08b08ab3e2296819a40f0ef82fc2cc Duration:157ms Memory:128MB MemUsage:23.976562MB

![截屏2020-03-0123 31 10](https://user-images.githubusercontent.com/43226363/75628549-2307be00-5c15-11ea-86be-3d990b426c3d.png)

**Comment by xytoki** [comment]
我果然专业生产bug x
明天debug

**Comment by xytoki** [comment]
2.8把类结构重构了一遍 一下又带来一大堆bug

**Comment by xytoki** [comment]
2.8.3已修复
