### ISSUE TITLE
新版本问题

### ISSUE THREAD

**Issue by dakaliu** [xytoki/TCShare#28]
使用https后访问时会莫名报错。
希望加密后的目录中的文件直链可以不通过密码访问。只是访问目录需要密码。

**Comment by dakaliu** [comment]
我尝试着加密目录/test/*这样子直链也需要密码，/test/这样子直链不需要密码但是通过url如/test/a/可以不输入密码列出test下目录a中的文件。

**Comment by xytoki** [comment]
https报错什么？
只加密文件夹可以写正则。看一下路由的文档。

**Comment by dakaliu** [comment]
![TIM图片20200303103950](https://user-images.githubusercontent.com/60661004/75737681-59d7f400-5d3b-11ea-8f5a-92cd5d3dc2f7.png)
经常性的这样出错

**Comment by xytoki** [comment]
http2-protocol-error是你服务器问题，php都还没执行连接就断了，与本程序无关。

**Comment by Nine55** [comment]
求只加密文件夹可以写正则，怎么写的新手不懂啊~~

**Comment by xytoki** [comment]
HTTP2错误疑似找到原因，试试删了这行看看还会不会http2错误
https://github.com/xytoki/TCShare/blob/253393b93e341cf8c8f9881343a0fa3c8ed868d7/_app/lib/Provider.php#L30

**Comment by xytoki** [comment]
已修复。
