### ISSUE TITLE
SCF中无法按文件名、修改时间、大小排序；点击网盘根目录按钮报错

### ISSUE THREAD

**Issue by littleBanshee** [xytoki/TCShare#30]
遇到2个问题，求助一下。
1.~~SCF中无法按文件名、修改时间、大小排序；~~
2.点击网盘根目录按钮报错，信息如下：
{"message":"There is no api match uri '\/' host 'service-xxx.apigw.tencentcs.com'"}
而实际网盘根目录为：service-xxx.apigw.tencentcs.com/release/函数名

**Comment by littleBanshee** [comment]
[问题1已经找到作者回答](https://github.com/xytoki/TCShare/issues/7#issuecomment-584462617)

**Comment by xytoki** [comment]
排序加上了。根目录那个是scf的问题，后续会修。

**Comment by xytoki** [comment]
已修复。

**Comment by littleBanshee** [comment]
> 已修复。

谢谢
