### ISSUE TITLE
开启redis缓存报错，Cannot find the "redis" extension nor the "predis/predis"

### ISSUE THREAD

**Issue by HisingX** [xytoki/TCShare#31]
Cannot find the "redis" extension nor the "predis/predis" package: redis://127.0.0.1:6379 (0)

**Comment by HisingX** [comment]
> Cannot find the "redis" extension nor the "predis/predis" package: redis://127.0.0.1:6379 (0)

问题关闭，用composer安装predis可解决，但是我也遇到了。

https://github.com/xytoki/TCShare/issues/28#issuecomment-593737170

这个http2错误，很奇怪的是在旧版本没有遇到过。

**Comment by xytoki** [comment]
http2错误现在不清楚是什么原因，有说法说可能是被q干扰了。

**Comment by HisingX** [comment]
> http2错误现在不清楚是什么原因，有说法说可能是被q干扰了。

我是腾讯云国内的服务器，很奇怪啊，http没事因为http也不用http2这个协议。
我感觉是缓存问题？因为第一次访问后网站不是就有缓存了，在一定时间内再次刷新，包括强制刷新也不会报错。

**Comment by xytoki** [comment]
> 我感觉是缓存问题？因为第一次访问后网站不是就有缓存了，在一定时间内再次刷新，包括强制刷新也不会报错。

缓存只缓存到天翼云的请求，理论上不会影响。你可以试试删了这几行（就会禁用缓存），看看还会不会有问题
https://github.com/xytoki/TCShare/blob/253393b93e341cf8c8f9881343a0fa3c8ed868d7/_app/providers/ctyun.php#L23-L26

**Comment by xytoki** [comment]
疑似找到原因，试试删了这行看看还会不会http2错误
https://github.com/xytoki/TCShare/blob/253393b93e341cf8c8f9881343a0fa3c8ed868d7/_app/lib/Provider.php#L30

**Comment by xytoki** [comment]
debug信息输出不要也没事，删了也不会影响。不过这种狗写法本来是为了兼容scf的...scf下不这么写它不输出...

**Comment by HisingX** [comment]
>              \Flight::response()->header( "X-TCS-Cache".str_repeat(" ",strlen($key)), "Missed ".$key);

注释掉后正常了，没有在提示HTTP2的错误

**Comment by xytoki** [comment]
行...我下版修复。
