### ISSUE TITLE
关于文档预览

### ISSUE THREAD

**Issue by zeroyearn** [xytoki/TCShare#34]
无法打开文档，多种格式均已测试
错误如图
![Screenshot_20200316-165309__01](https://user-images.githubusercontent.com/16523898/76739127-c543ac00-67a6-11ea-94ad-e31e33aeaf9c.jpg)
点击learn more网页无法打开

**Comment by xytoki** [comment]
能给个测试地址吗。我暂时无法复现，不太清楚是哪里问题。

**Comment by zeroyearn** [comment]
[tcs](https://tcs.52qdg.com)

**Comment by xytoki** [comment]
尝试更一下现在v2分支的版本，刚刚修了一个bug，不知道会不会相关。我这里测试用户下载文件正常，但是确实无法通过预览服务器连接。

**Comment by zeroyearn** [comment]
已尝试最新版本，但文档依旧无法打开

**Comment by xytoki** [comment]
再试下最新版。尝试改了一下逻辑，不知道有没有好一些

**Comment by zeroyearn** [comment]
更新最新版本已解决
