### ISSUE TITLE
图片列表功能

### ISSUE THREAD

**Issue by thericeman** [xytoki/TCShare#35]
**What feature do you want?**
目前所有的文件都是列出详细信息，如果碰到是图片的目录，也是一样，感知较差。

**Describe the solution you'd like**
自动判断目录属性，发现绝大部分是图片，则像windows一样，自动改为显示缩略图，或者分页显示图片

**Additional context**
缩略图可能会用到本地存储和流量，感觉不现实，做不到的话可以考虑每页显示9个图片。

**Comment by xytoki** [comment]
右下角按钮可以切换缩略图，目前仅天翼云支持。
自动判断目录属性的话，会考虑加入，不会消耗服务器存储，但是会产生更多的API调用导致速度降低。

**Comment by lrpli** [comment]
实测天翼云和od国际版支持，世纪互联不支持

**Comment by xytoki** [comment]
我就说怎么文档里的缩略图接口什么都不返回....结果是世纪互联的问题...
那我后面给世纪互联加个hack吧...

**Comment by qkqpttgf** [comment]
> 我就说怎么文档里的缩略图接口什么都不返回....结果是世纪互联的问题...
> 那我后面给世纪互联加个hack吧...

世纪互联是支持thumb的

**Comment by xytoki** [comment]
> > 我就说怎么文档里的缩略图接口什么都不返回....结果是世纪互联的问题...
> > 那我后面给世纪互联加个hack吧...
> 
> 世纪互联是支持thumb的

是支持，但是必须单独查询thumb接口，如果合并请求列表和缩略图就不会返回数据，国际版可以。
微软接口里是可以用`$expand=thumbnails`合并请求的，但是世纪互联就是有时可以有时不可以。

**Comment by qkqpttgf** [comment]
> > > 我就说怎么文档里的缩略图接口什么都不返回....结果是世纪互联的问题...
> > > 那我后面给世纪互联加个hack吧...
> > 
> > 
> > 世纪互联是支持thumb的
> 
> 是支持，但是必须单独查询thumb接口，如果合并请求列表和缩略图就不会返回数据，国际版可以。
> 微软接口里是可以用`$expand=thumbnails`合并请求的，但是世纪互联就是有时可以有时不可以。

好吧，没有在expand里面加过thumbnails。
