### ISSUE TITLE
希望可以增加音频预览播放功能

### ISSUE THREAD

**Issue by WangWenBin2017** [xytoki/TCShare#37]
**What feature do you want?**
请清晰描述你想要的功能
希望可以在web页面直接播放音乐,且可以通过配置文件来设定哪些后缀为music类型

**Describe the solution you'd like**
如果可以，请尝试提出可能的解决方案
具体代码可以参考OneIndex对于音频的解决方案

**Additional context**
其他你想说的
暂无,期待大佬开发

**Comment by xytoki** [comment]
`v3.1.3`已加

**Comment by WangWenBin2017** [comment]
感谢大佬，马上更新看看～

**Comment by xytoki** [comment]
音频同时支持同名歌词文件，虽然没啥用

**Comment by WangWenBin2017** [comment]
同名歌词放在同级目录下么，还有文件类型在哪个文件呢，想增加对flac和ape格式的支持

**Comment by WangWenBin2017** [comment]
chrome浏览器可以解码flac和ape

**Comment by xytoki** [comment]
> chrome浏览器可以解码flac和ape

flac 原来就有，配置在这，ape下版本给加上
https://github.com/xytoki/TCShare/blob/00a0690f6e383d8b668c07e3a724696def0cc74a/_app/views/readypreview.js#L4-L11

**Comment by xytoki** [comment]
> 同名歌词放在同级目录下么，还有文件类型在哪个文件呢，想增加对flac和ape格式的支持

对，同级目录，参考：https://xia.st/音乐/
