### ISSUE TITLE
希望添加密码目录 以及分离开视频播放 跟下载

### ISSUE THREAD

**Issue by linhai1993** [xytoki/TCShare#4]
希望增加参数 .mp4/?play  或者.mp4/?download 来区分 在线播放 还是下载动作。或者提供相似功能。

**Comment by xytoki** [comment]
mdui主题点击视频文件名为预览，右侧下载按钮为下载，缩略图模式点击视频文件会询问动作

**Comment by xytoki** [comment]
同时get请求为下载，post请求或?TC_preview为预览。目录加密下个版本更新。

**Comment by xytoki** [comment]
dcca5c4c0f466ebf89faf8028fbcd4c9a1cce6c4
防盗链和密码保护已完成。
