### ISSUE TITLE
希望可以增加README.md显示和某种后缀名的文件不显示

### ISSUE THREAD

**Issue by WangWenBin2017** [xytoki/TCShare#40]
**What feature do you want?**
请清晰描述你想要的功能
1.扫描云盘访问的目录下是否有README.md文件,如果有的话可以以markdown格式显示出来
2.设置某种文件类型不显示,比如歌词lrc文件

**Describe the solution you'd like**
如果可以，请尝试提出可能的解决方案
第一个建议的话同样也是隔壁oneindex具备的功能,我觉得既然歌词lrc能显示这个肯定也行吧[狗头]
第二个的话个人感觉加判断应该可以,我不是很精通php,不行的话勿喷

**Additional context**
其他你想说的
就这些吧,测试可用后最好SCF再测试一下,感谢

**Comment by xytoki** [comment]
readme，会有的，但是没那么快。
文件隐藏，在考虑实现放弃，比如隐藏的文件能预览吗？能被一键复制链接吗？这样的。

**Comment by WangWenBin2017** [comment]
感觉可以预览就行吧,感觉增加选项设置能否预览的话代码会很冗余...还有一个问题就不提issues了,能否实现播放器加载歌词的通知自动加载同目录下同文件名的图片作为封面呢,准备做个hi-res的文件目录,但是没有介绍和播放器封面图就不大好整

**Comment by xytoki** [comment]
可以的，会加上。这段时间在优化视频播放(自定义搜索字幕不强求同名那种)，后面会看情况把歌词和封面也改成这个逻辑

**Comment by WangWenBin2017** [comment]
嗯,慢慢来,大佬加油

**Comment by WangWenBin2017** [comment]
再来一个建议,如果可以的话能否加上无刷新加载?现在播放器一切换目录音乐就停了

**Comment by xytoki** [comment]
> 再来一个建议,如果可以的话能否加上无刷新加载?现在播放器一切换目录音乐就停了

无刷新加载暂时不会考虑。

**Comment by WangWenBin2017** [comment]
好吧

**Comment by xytoki** [comment]
readme已加上。

**Comment by WangWenBin2017** [comment]
嗯，再提一下歌曲图片的逻辑吧，可以这样，先检查有没有音乐文件同名的图片文件，有优先加载，默认保持和readme.md一样的隐藏逻辑；若没有，再次检查是否有cover.jpg，有的话就加载这个，啥都没有就没图片，这样。
