### ISSUE TITLE
电脑上视频播放只有声音没有画面

### ISSUE THREAD

**Issue by r1172464137** [xytoki/TCShare#41]
**Describe the bug 症状是什么？**
电脑端在线播放视频只有声音没有画面
但手机端是能播放的

**Screenshots 截图/报错日志**
![批注 2020-03-31 213853](https://user-images.githubusercontent.com/29038520/78033113-89a90480-7398-11ea-8fa0-35816bf36b0d.png)
![Screenshot_2020-03-31-21-40-47-478_com microsoft](https://user-images.githubusercontent.com/29038520/78033154-94639980-7398-11ea-8d0c-f62736a34d49.jpg)

**Additional context 其他信息**
我的运行环境是宝塔，php7.4版本，转码开启和关闭也试过了，但电脑端就是死活没画面。

**Comment by xytoki** [comment]
1.转码仅和彩云，天翼云不支持
2.如果视频是HEVC/H.265编码，电脑黑屏手机能放是正常现象，请检查一下视频编码格式

**Comment by r1172464137** [comment]
谢谢大佬，我的编码格式确实是属于hevc，所以没法播放
