### ISSUE TITLE
从3.1.6版本开始，Token鉴权功能无法正常使用。

### ISSUE THREAD

**Issue by okok-666** [xytoki/TCShare#42]
**Describe the bug 症状是什么？**
从3.1.6版本开始，Token鉴权功能无法正常使用。

**To Reproduce  怎么出现的？**
访问相关链接时出现密码保护页面。

**Expected behavior 本该怎么样？**
3.1.6版本之前的均正常，从3.1.6版本开始Token鉴权功能无法正常使用。

**Screenshots 截图/报错日志**

**Additional context 其他信息**

**Comment by xytoki** [comment]
试一下v3分支最新版，应该修复了。

**Comment by xytoki** [comment]
是否已解决？我先关闭issue，如仍有问题，请reopen。
