### ISSUE TITLE
使用github action部署到php空间

### ISSUE THREAD

**Issue by BlueHtml** [xytoki/TCShare#43]
**What feature do you want?**
请清晰描述你想要的功能

使用github action部署到php空间

**Describe the solution you'd like**
如果可以，请尝试提出可能的解决方案

使用github action还原依赖，并把生成后的文件使用FTP上传到php空间。

**Additional context**
其他你想说的

写了篇博客：[使用PHP空间和天翼云盘搭建私人云盘](https://blog.guoqianfan.com/2020/03/22/shared-cloud-with-tc/)

**Comment by xytoki** [comment]
感谢支持，我会把这条issue置顶供他人参考。
