### ISSUE TITLE
可否增加webdav功能？谢谢

### ISSUE THREAD

**Issue by whyun1** [xytoki/TCShare#44]
**What feature do you want?**
请清晰描述你想要的功能

webdav导出功能

 feature do you want?**
请清晰描述你想要的功能

可否增加Webdav导出功能?方便电视和手机上直接用播放器观看视频。

**Describe the solution you'd like**
如果可以，请尝试提出可能的解决方案

**Additional context**
其他你想说的

**Comment by xytoki** [comment]
可能会尝试，但是webdav会只读，无法写入。

**Comment by whyun1** [comment]
能读就可以。感谢大佬，速度一流啊！！
