### ISSUE TITLE
SCF环境WebDAV挂载失败

### ISSUE THREAD

**Issue by damonliguo** [xytoki/TCShare#45]
**Describe the bug 症状是什么？**
webdav挂载失败，返回错误404

**Screenshots 截图/报错日志**
![截屏2020-04-09 18 53 46](https://user-images.githubusercontent.com/43226363/78888125-a8438580-7a93-11ea-9707-d7fd4815f650.png)

**Comment by xytoki** [comment]
scf吗？由于dav库和scf不兼容，scf不支持webdav。

**Comment by damonliguo** [comment]
哦哦，好的
