### ISSUE TITLE
vps挂载webdav失败  网站可正常访问

### ISSUE THREAD

**Issue by wzirun** [xytoki/TCShare#46]
vps挂载webdav失败  网站可正常访问 
#   这里APP后面的可以是任意值，一般就123456下去
#          ↓
    XS_APP_1=/              #挂载路径
    XS_APP_1_NAME=TCShare   #网盘名称
    XS_APP_1_THEME=mdui     #界面主题
    XS_APP_1_BASE=/         #网盘内路径
    XS_APP_1_KEY=ct        #对应上面Key的ID
    XS_APP_ct_DAV=true

配置文件
win10自带客户端  服务器 centos 7   php7.2

**Comment by xytoki** [comment]
配置写错了，
`XS_APP_1_DAV=true`
