### ISSUE TITLE
Webdav 无法使用应用读取

### ISSUE THREAD

**Issue by cxyzzz** [xytoki/TCShare#47]
**Describe the bug 症状是什么？**

webdav 无法使用应用读取，尝试了fooview、nPlayer、Mixplorer均无法连接。使用浏览器访问webdav正常。

**To Reproduce  怎么出现的？**

**Expected behavior 本该怎么样？**

**Screenshots 截图/报错日志**
![IMG_20200410_185043](https://user-images.githubusercontent.com/21036341/78985792-3aaf5c00-7b5c-11ea-9dd7-cb55c7e8a764.jpg)
![Screenshot_2020-04-10-18-51-46-663_com mixplorer silver](https://user-images.githubusercontent.com/21036341/78985843-5dda0b80-7b5c-11ea-8046-2a09977b55cb.jpg)

**Additional context 其他信息**

**Comment by xytoki** [comment]
看第二张图提示好像是405错误，请尝试配置一下nginx，加到rewrite里。
```nginx
set $sep "?";
if ( $is_args = "?" ){
    set $sep "&";
}
error_page  405 =200 $uri${sep}_FORCE_METHOD=$request_method;
```

**Comment by cxyzzz** [comment]
@xytoki 可以了，多谢
