### ISSUE TITLE
在线视频播放添加参数阻止下载

### ISSUE THREAD

**Issue by FFFcat** [xytoki/TCShare#48]
**What feature do you want?**
请清晰描述你想要的功能

直接在网页输入视频网址会直接下载，只能通过网页点击才能重定向到在线观看，希望能在视频网址添加参数例如`?a=view`实现阻止下载，且能在线观看。

**Describe the solution you'd like**
如果可以，请尝试提出可能的解决方案

看到goindex有感而发，下面是相关代码定位
[L147](https://github.com/donwa/goindex/blob/9f5b55f2fbcc4504456fea177a0dbba14327130c/themes/material/app.js#L147)
[L183](https://github.com/donwa/goindex/blob/9f5b55f2fbcc4504456fea177a0dbba14327130c/themes/material/app.js#L183)

**Comment by xytoki** [comment]
已实现: ?TC_preview，这个一直都有。
其他参数还有?TC_direct，小于1m的文件服务器中转
?_tcshare_renew 强制刷新缓存

**Comment by FFFcat** [comment]
原来是这样，看代码的时候没发现这个，谢谢。
