### ISSUE TITLE
关于天翼云API key申请

### ISSUE THREAD

**Issue by cxyzzz** [xytoki/TCShare#49]
**What feature do you want?**
请清晰描述你想要的功能

这里可以创建个人存储类的应用，并且不需要等待审核就能获取到APP ID和secret，不知道能不能用？
<http://open.189.cn/index.php?m=ability&c=index&a=show&id=333>

![Screenshot_2020-04-11-00-29-19-897_com android chrome](https://user-images.githubusercontent.com/21036341/79006703-4e72b680-7b8c-11ea-83ac-cd32977ec368.jpg)

**Describe the solution you'd like**
如果可以，请尝试提出可能的解决方案

**Additional context**
其他你想说的

**Comment by xytoki** [comment]
我自己测试申请的key无法调用api。你可以找相关sdk试一下。
