### ISSUE TITLE
请问一下，SCF如何禁用-install等参数

### ISSUE THREAD

**Issue by FFFcat** [xytoki/TCShare#54]
**What feature do you want?**
请清晰描述你想要的功能

在配置好环境后，怕有人恶意修改，在服务器上面可以配置nginx规则禁止，但在SCF上摸不着头脑，因此想问下能不能手动开关-install、-renew、-callback三个参数。

**Comment by xytoki** [comment]
环境变量填入
```shell
XS_CONFIG_PASS='你的密码'
```
即可对-install、-renew、-callback加密。

**Comment by FFFcat** [comment]
好的，谢谢。再重新看一遍历史代码，仔细看看是8天前加的，(*^▽^*)

**Comment by xytoki** [comment]
此前也没有问题的，天翼云的每个账号accesstoken都是固定的，原先是只允许同一个账户绑定。
