### ISSUE TITLE
宝塔里面部署失败 提示：Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/www/index.php on line 7

### ISSUE THREAD

**Issue by shandian110** [xytoki/TCShare#6]
宝塔里面部署失败 提示：Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/www/index.php on line 7

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/www/index.php on line 7

**Comment by xytoki** [comment]
请自行使用composer安装依赖。
